@startuml

class vehicle {
  type *  : enum 
  owner *  : array 
  registration *  : registration 
}

vehicle *-- owner : owner

vehicle -- registration : registration

class landVehicle {
  wheels *  : integer 
}
vehicle <|-- landVehicle

class waterVehicle {
  propeller *  : integer 
}
vehicle <|-- waterVehicle

class airVehicle {
  name : string 
  
  engines *  : integer 
  typeOfEngine *  : enum 
}
vehicle <|-- airVehicle

class owner {
  name *  : string 
  from *  : date 
  to : date 
}

class registration {
  code *  : string 
  firstRegistration *  : date 
  registrationEnd : date 
  country *  : enum 
}
@enduml
