@startuml

class landVehicle {
  wheels *  : integer <[minimum:2][maximum:4][multipleOf:2]>
}
vehicle <|-- landVehicle

class waterVehicle {
  propeller *  : integer <[minimum:1][maximum:4]>
}
vehicle <|-- waterVehicle

class airVehicle {
  name : string <[maxLength:20]>
  engines *  : integer <[minimum:1][maximum:6]>
  typeOfEngine *  : enum <[turbojet, turboprop, turbofan, turboshaft]>
}
vehicle <|-- airVehicle

class vehicle {
  type *  : enum <[land, air, water]>
  owner *  : array[] of owner <[minItems:1]>
  registration *  : registration 
}

vehicle *-- owner : owner

vehicle -- registration : registration

class owner {
  name *  : string 
  from *  : date 
  to : date 
  age *  : integer 
  nicknames : array[] of strings 
  gender : enum 
  file1 : string [binary] 
  file2 : string [byte] 
  shoeSize : integer 
  someDouble : integer 
}

class registration {
  code *  : string 
  firstRegistration *  : date 
  registrationEnd : date 
  country *  : enum 
}
@enduml
