name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Bump version and push to GitHub
      run: |
        npm version patch  # Increment the version number (you can use "minor" or "major" instead of "patch" if needed)
        git commit -am "Bump version for release"
        git push

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
